Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_version = "12.20250126.1"


	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 2
	end

	config.vm.provision "shell", path: "scripts/common.sh"

	config.vm.define "server" do |server|
		server.vm.hostname = "kasinghS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", inline: 'echo "✅ Server ready"'
	end

	config.vm.define "worker" do |worker|
		worker.vm.hostname = "kasinghSW"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provision "shell", inline: 'echo "✅ Worker ready"'
	end



end
