Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_version = "12.20250126.1"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.define "kasinghS" do |server|
        server.vm.hostname = "kasinghS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 8080, host: 9090
        # server.vm.provision "shell", path: "scripts/setup.sh"
        # server.vm.provision "shell", path: "scripts/init.sh"
        server.vm.provision "shell", inline: 'echo "✅ Server ready"'
    end
end